name = "lean_to_lambdabox"
version = "0.1.0"
defaultTargets = ["LeanToLambdaBox"]

[[lean_lib]]
name = "LeanToLambdaBox"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "v4.24.0"
